/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b2019c1a-b79d-4594-b065-bd43f0bce01b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_CHNlu9uKj",
    "aws_user_pools_web_client_id": "4q3m4l24u503umrvghvt0sobho",
    "oauth": {}
};


export default awsmobile;
